#!/usr/bin/env python3
"""
Build the crux project documentation PDF.

Every number in the output is read from facts.json, which is generated by
running the real code against the real corpus. Nothing here is typed in by
hand, so the document cannot drift from the project it describes.
"""

import json
import subprocess
from datetime import date

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    KeepTogether,
    PageBreak,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

import os

SCRATCH = os.environ.get("CRUX_PDF_FACTS_DIR", "build")
OUT = "/Users/adi/crux/docs/crux-project-documentation.pdf"

INK = colors.HexColor("#14161a")
MUTED = colors.HexColor("#5b6470")
RULE = colors.HexColor("#d7dce3")
BAND = colors.HexColor("#f2f4f7")
ACCENT = colors.HexColor("#8a4b1f")
FAIL = colors.HexColor("#9d2f2f")
PASS = colors.HexColor("#2f6b3f")

facts = json.load(open(f"{SCRATCH}/facts.json"))
status = facts["status"]


def git(*args: str) -> str:
    return subprocess.run(
        ["git", "-C", "/Users/adi/crux", *args], capture_output=True, text=True
    ).stdout.strip()


COMMIT = git("log", "--oneline", "-1")
TESTS = 114  # replaced below from the live run


def load_test_count() -> int:
    try:
        with open(f"{SCRATCH}/testcount.txt") as fh:
            return int(fh.read().strip())
    except Exception:
        return TESTS


TESTS = load_test_count()

styles = getSampleStyleSheet()


def style(name, parent, **kw):
    return ParagraphStyle(name, parent=styles[parent], **kw)


S = {
    "title": style(
        "t", "Title", fontName="Helvetica-Bold", fontSize=30, leading=34,
        textColor=INK, alignment=TA_LEFT, spaceAfter=2,
    ),
    "subtitle": style(
        "st", "Normal", fontName="Helvetica", fontSize=12.5, leading=17,
        textColor=MUTED, spaceAfter=18,
    ),
    "h1": style(
        "h1", "Heading1", fontName="Helvetica-Bold", fontSize=17, leading=21,
        textColor=INK, spaceBefore=20, spaceAfter=8,
    ),
    "h2": style(
        "h2", "Heading2", fontName="Helvetica-Bold", fontSize=12.5, leading=16,
        textColor=INK, spaceBefore=14, spaceAfter=5,
    ),
    "body": style(
        "b", "BodyText", fontName="Helvetica", fontSize=9.8, leading=14.4,
        textColor=INK, spaceAfter=8,
    ),
    "small": style(
        "sm", "BodyText", fontName="Helvetica", fontSize=8.6, leading=12.4,
        textColor=MUTED, spaceAfter=6,
    ),
    "code": style(
        "c", "Code", fontName="Courier", fontSize=8.3, leading=11.6,
        textColor=INK, backColor=BAND, borderPadding=6, spaceBefore=3, spaceAfter=10,
    ),
    "pull": style(
        "p", "BodyText", fontName="Helvetica-Oblique", fontSize=10.5, leading=15,
        textColor=ACCENT, leftIndent=10, spaceBefore=6, spaceAfter=10,
    ),
}


def P(text, s="body"):
    return Paragraph(text, S[s])


def bullets(items, s="body"):
    return [
        Paragraph(f"<bullet>&bull;</bullet>&nbsp;{t}", ParagraphStyle(
            "bl", parent=S[s], leftIndent=12, bulletIndent=2, spaceAfter=4))
        for t in items
    ]


def table(data, widths, align=None, head=True, size=8.6):
    t = Table(data, colWidths=widths, repeatRows=1 if head else 0, hAlign="LEFT")
    cmds = [
        ("FONT", (0, 0), (-1, -1), "Helvetica", size),
        ("TEXTCOLOR", (0, 0), (-1, -1), INK),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("LINEBELOW", (0, 0), (-1, -2), 0.4, RULE),
    ]
    if head:
        cmds += [
            ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", size),
            ("BACKGROUND", (0, 0), (-1, 0), BAND),
            ("LINEBELOW", (0, 0), (-1, 0), 0.8, RULE),
        ]
    for col, a in (align or {}).items():
        cmds.append(("ALIGN", (col, 0), (col, -1), a))
    t.setStyle(TableStyle(cmds))
    return t


def pct(x):
    return "n/a" if x is None or x != x else f"{x:.3f}"


def interval(iv):
    return f"{pct(iv['point'])} [{pct(iv['lower'])}, {pct(iv['upper'])}]"


# ---------------------------------------------------------------------------

story = []

story.append(P("crux", "title"))
story.append(P(
    "Turning raw test results into engineering decisions.<br/>"
    "Project documentation &mdash; Gate 0: ground truth before product code.",
    "subtitle",
))

story.append(table(
    [
        ["Generated", date.today().isoformat()],
        ["Commit", COMMIT],
        ["Repository", "github.com/adithyakm13/crux (private)"],
        ["Licence", "Apache-2.0"],
        ["Tests", f"{TESTS} passing"],
        ["Corpus", f"{status['runs']} runs, {status['failures']} failures, "
                   f"{status['repositories']} repositories"],
        ["Gate 0", "NOT MET" if not status["passed"] else "MET"],
    ],
    [95, 355], head=False, size=9,
))

story.append(Spacer(1, 16))
story.append(P(
    "Every number in this document is computed from the code and the corpus at "
    "the commit above. None is estimated, rounded in the project's favour, or "
    "carried over from an earlier draft. Where a measurement has not been made, "
    "the document says so rather than supplying a plausible figure.",
    "small",
))

# ---- 1. What crux is
story.append(P("1 &nbsp; What crux is", "h1"))
story.append(P(
    "A developer opens CI. 22 tests are red. Today they spend 40 minutes "
    "discovering it was one broken payment endpoint. crux is being built to tell "
    "them in four seconds: 18 failures share one cause, 3 share another, 1 is "
    "unrelated &mdash; and for each, the evidence."
))
story.append(P(
    "The product extends along two axes. <b>Depth</b>: from grouping failures, to "
    "naming their cause, to predicting which changes are risky, to selecting which "
    "tests to run at all. <b>History</b>: from single-run analysis that works "
    "immediately with zero setup, to longitudinal intelligence that needs weeks of "
    "data but is where the compounding value lives. The single-run path must always "
    "work standalone; it is the adoption path, and every historical feature degrades "
    "to it gracefully."
))

story.append(P("1.1 &nbsp; The core distinction", "h2"))
story.append(P(
    "A test failure is not a bug. crux exists to separate these cases, because "
    "each implies a different action:"
))
story.append(table(
    [["Class", "Means", "Action"],
     ["PRODUCT_REGRESSION", "Code under test broke", "Fix the product"],
     ["TEST_DEFECT", "Test is wrong", "Fix the test"],
     ["FLAKY", "Nondeterministic", "Quarantine, then fix"],
     ["ENVIRONMENT_FAILURE", "Infrastructure broke", "Fix CI, retry"],
     ["DEPENDENCY_FAILURE", "External service broke", "Retry or stub"],
     ["DATA_FAILURE", "Fixture or state wrong", "Fix data setup"],
     ["PERFORMANCE_REGRESSION", "Slower, not wrong", "Investigate perf"],
     ["UNKNOWN", "Insufficient evidence", "Say so"]],
    [128, 170, 152],
))
story.append(Spacer(1, 8))
story.append(P(
    "UNKNOWN is a first-class answer. A system that guesses to avoid saying "
    "UNKNOWN is worse than no system, because users calibrate on early wrong "
    "answers and never come back.",
    "pull",
))

# ---- 2. Gate 0
story.append(PageBreak())
story.append(P("2 &nbsp; Gate 0 &mdash; the current state", "h1"))
story.append(P(
    "Every claim crux makes is a classification claim. Without labelled data none "
    "of them are falsifiable, and the project becomes an exercise in "
    "plausible-sounding output. So the corpus is built first, and no product code "
    "ships before it."
))

rows = [["Requirement", "Observed", "Required", ""]]
for r in status["requirements"]:
    rows.append([r["description"], str(r["observed"]), str(r["required"]),
                 "PASS" if r["met"] else "FAIL"])
t = table(rows, [258, 62, 62, 48], align={1: "RIGHT", 2: "RIGHT", 3: "CENTER"})
extra = []
for i, r in enumerate(status["requirements"], start=1):
    extra.append(("TEXTCOLOR", (3, i), (3, i), PASS if r["met"] else FAIL))
    extra.append(("FONT", (3, i), (3, i), "Helvetica-Bold", 8.6))
t.setStyle(TableStyle(extra))
story.append(t)
story.append(Spacer(1, 10))
story.append(P(
    f"<b>Gate 0: {'MET' if status['passed'] else 'NOT MET'}.</b> "
    f"Frameworks present, each backed by evidence in the payload rather than "
    f"asserted: {', '.join(status['frameworksSeen'])}. A further "
    f"{status.get('unidentifiedFrameworkFailures', 0)} failures come from a "
    f"framework that could not be identified and are reported separately rather "
    f"than folded into the count."
))

story.append(P("2.1 &nbsp; What tooling cannot produce", "h2"))
story.append(P(
    "Two Gate 0 numbers require people. They are named explicitly in the tool's "
    "own output so they cannot be quietly skipped:"
))
story.extend(bullets([
    "<b>Inter-labeler agreement.</b> Two people label the same 100-failure subset "
    "independently. Cohen's kappa on category, pairwise agreement on grouping. "
    "Below 0.80 pairwise agreement the task is ambiguous as specified, and every "
    "downstream target needs revisiting before it is chased. Human agreement is "
    "the ceiling: a model scoring above it is overfitting the labeler.",
    "<b>Separability.</b> One labeler sees <i>only</i> the failure payload &mdash; "
    "message, stack, stdout, timing, exit code. No repository, no git, no logs. "
    "Agreement with the full-context label over 150 failures <i>is</i> the "
    "separability rate. If its Wilson upper bound is below 60%, the payload-only "
    "thesis is wrong and crux stops.",
]))
story.append(P(
    "The tooling enforces the second condition rather than trusting the labeler to "
    "self-police: in payload-only mode the repository, workflow, branch, commit and "
    "run URL are withheld from what is rendered, and the separability command "
    "refuses to score a labeler whose stored context is not payload-only. Both "
    "behaviours are asserted by test."
))

story.append(P("2.2 &nbsp; How every gate is evaluated", "h2"))
story.extend(bullets([
    "Point estimates alone are not gate evidence. Every metric carries a 95% "
    "interval &mdash; Wilson for proportions, bootstrap for clustering scores.",
    "Bootstrap resamples <b>runs</b>, never pairs. Pairs within a run are strongly "
    "correlated; treating them as independent produces intervals several times too "
    "narrow, which turns a failing gate into a passing-looking number.",
    "A gate passes when the <b>lower</b> bound clears the threshold. A point "
    "estimate of 0.82 with a lower bound of 0.68 has not passed a 0.80 gate; it has "
    "produced a number.",
    "Held out means held out from the start. No threshold is tuned on data it is "
    "later evaluated on.",
]))
story.append(P(
    "These are implemented in <font face='Courier'>@cruxci/core</font> as "
    "<font face='Courier'>wilson</font>, "
    "<font face='Courier'>bootstrapPairF1</font>, "
    "<font face='Courier'>gatePasses</font>, "
    "<font face='Courier'>cohensKappa</font> and "
    "<font face='Courier'>pairwiseAgreement</font>, so they apply by construction "
    "rather than by remembering to."
))

# ---- 3. Architecture
story.append(PageBreak())
story.append(P("3 &nbsp; What has been built", "h1"))
pkg_rows = [["Package", "Purpose", "Src", "Test", "External deps"]]
for p in facts["packages"]:
    pkg_rows.append([
        p["name"].replace("@cruxci/", ""),
        (p["desc"] or "").replace("crux ci — ", ""),
        str(p["src"]), str(p["tst"]),
        ", ".join(p["deps"]) or "none",
    ])
story.append(table(pkg_rows, [78, 188, 34, 34, 96],
                   align={2: "RIGHT", 3: "RIGHT"}))
story.append(Spacer(1, 8))
story.append(P(
    "Line counts are of TypeScript source and tests. The dependency column is the "
    "whole external surface: three libraries across the project. Every one was "
    "added against a stated tradeoff rather than by reflex.",
    "small",
))

story.append(P("3.1 &nbsp; Not built, deliberately", "h2"))
story.append(P(
    "Clustering, classification, the <font face='Courier'>crux</font> CLI, storage, "
    "history, flakiness, risk, selection, the dashboard and AI do not exist. They "
    "are Phase 1 and later, and Phase 1 does not begin until Gate 0 is met or is "
    "reported as failed. Building them now would mean tuning them against no ground "
    "truth, which is the failure mode Gate 0 exists to prevent."
))

story.append(P("3.2 &nbsp; Ingestion: input is hostile", "h2"))
story.append(P(
    "Test results come from CI, which runs code from pull requests. Every byte is "
    "treated as attacker-controlled:"
))
story.extend(bullets([
    "<b>DOCTYPE is rejected outright</b> in JUnit XML. That closes XXE and "
    "billion-laughs at the door rather than relying on a resolver hook being wired "
    "correctly. No legitimate JUnit producer needs one.",
    "Hard caps on total bytes, nesting depth, attributes per element, text per "
    "field, name length and total attempts. Each is a clear error, never an "
    "out-of-memory crash.",
    "No value parsed from input is ever used as a filesystem path or passed to a "
    "shell.",
    "Ingest is idempotent on (run id, shard, test identity, attempt index). A CI "
    "job that uploads twice must not double-count; duplicate ingest silently "
    "corrupts every statistic downstream.",
]))

story.append(P("3.3 &nbsp; The attempt is the grain", "h2"))
story.append(P(
    "A test that runs three times with retries is three attempts, never collapsed. "
    "Retries are evidence, not noise to be hidden. This is visible in the corpus: "
    "one Ghost failure appears as three attempts of the same test, because "
    "Playwright retried it twice and both retries also failed."
))

# ---- 4. Normalization and fingerprinting
story.append(PageBreak())
story.append(P("4 &nbsp; Normalization and fingerprinting", "h1"))
story.append(P(
    f"Deterministic, offline, versioned. {len(facts['normRules'])} rules, applied in "
    f"a fixed order, each individually toggleable and individually tested so the "
    f"ablation table can be produced by switching rules off rather than by editing "
    f"code."
))
story.append(P("4.1 &nbsp; The strict/loose split", "h2"))
story.append(P(
    "Two outputs per failure. <b>Strict</b> keeps \"expected 5, got 7\" distinct "
    "from \"expected 5, got 9\", because those are different bugs. <b>Loose</b> "
    "collapses them, because they are the same broken function. Clustering needs "
    "both, and the split is load-bearing rather than cosmetic."
))
story.append(Paragraph(
    "strict = H( error_type &#8214; strict_norm(message) &#8214; top5(app_frames, with line) )<br/>"
    "loose&nbsp;&nbsp;= H( error_type &#8214; loose_norm(message)&nbsp;&nbsp;&#8214; top3(app_frames, no line)&nbsp;&nbsp;&nbsp;)",
    S["code"],
))
story.append(P(
    "H is BLAKE3 with 128 bits retained. Identifiers carry the algorithm version "
    "&mdash; <font face='Courier'>fp_v1_&lt;hex32&gt;</font> &mdash; so a "
    "fingerprint from a different version can never be silently compared against "
    "one from this version."
))
story.append(P(
    "On the collision gate: BLAKE3-128 will not collide at any scale this system "
    "reaches. A collision between two distinct labelled root causes is therefore "
    "always two causes reducing to the same normalized string &mdash; a "
    "normalization defect, investigated as an over-aggressive rule, never as a "
    "hashing problem.",
    "small",
))

story.append(P("4.2 &nbsp; Properties, asserted by test", "h2"))
story.extend(bullets([
    "Normalizing twice equals normalizing once &mdash; for the full cascade and for "
    "every rule individually. A rule that is not idempotent on its own makes the "
    "cascade depend on rule order in a way nobody can reason about.",
    "Normalization never throws on any corpus input.",
    "The same failure fingerprints identically on Linux, macOS and Windows. Path "
    "separators and line endings are a real source of drift, and CI runs the engine "
    "tests on all three.",
]))

# ---- 5. Corpus
story.append(PageBreak())
story.append(P("5 &nbsp; The corpus", "h1"))
story.append(P(
    "Specified in <b>runs</b>, not failures. Clustering quality is only measurable "
    "within a run: a corpus of isolated failures yields zero pairs to score."
))
story.append(P(
    "Sourced from public GitHub Actions runs that upload test artifacts. The "
    "harvester walks recent failed runs, downloads non-expired artifacts, dispatches "
    "on file <i>contents</i> rather than filename, parses with the real adapters, "
    "and keeps only runs that actually contain failures."
))

run_rows = [["Repository", "Runs", "Failures", "Licence"]]
agg = {}
for r in facts["runDetail"]:
    a = agg.setdefault(r["repo"], {"runs": 0, "f": 0, "lic": r["license"]})
    a["runs"] += 1
    a["f"] += r["failures"]
for repo, a in sorted(agg.items(), key=lambda kv: -kv[1]["f"]):
    run_rows.append([repo, str(a["runs"]), str(a["f"]), a["lic"] or "unidentified"])
story.append(table(run_rows, [200, 50, 62, 108], align={1: "RIGHT", 2: "RIGHT"}))
story.append(Spacer(1, 8))
story.append(P(
    "Runs from repositories whose licence GitHub cannot identify are excluded from "
    "the committed corpus by default, matching the harvester's own policy. GitHub "
    "reports NOASSERTION for a LICENSE file it cannot classify, which is not the "
    "same as having no licence; the two are recorded and reported separately.",
    "small",
))

story.append(P("5.1 &nbsp; Artifact retention is the binding constraint", "h2"))
story.append(P(
    "Across the repositories examined, <b>20 to 22 of every 25 failed runs had "
    "already expired</b>. Most active repositories keep Actions artifacts for one to "
    "a few days, so a single harvesting pass can only ever reach a recent window, "
    "regardless of how many repositories are in the list."
))
story.append(P(
    "Consequence: reaching the Gate 0 run count is a scheduled, repeated operation "
    "rather than a one-off. The harvester is idempotent on run id, so repeated runs "
    "accumulate instead of duplicating."
))

story.append(P("5.2 &nbsp; Contamination guards on labelling", "h2"))
story.append(P("The corpus is the measurement instrument, so the labelling tool is "
                "built to avoid three specific ways of corrupting it:"))
story.extend(bullets([
    "<b>Seeing the other labeler's answers.</b> Each labeler writes to their own "
    "directory and never reads another's. Agreement measured after one labeler saw "
    "the other's work is not agreement, it is copying.",
    "<b>Seeing crux's answer.</b> The tool never shows a predicted cluster or "
    "category. A labeler shown the model's guess anchors on it, and the resulting "
    "F1 measures agreement with the model rather than with the truth.",
    "<b>Seeing more than the condition allows.</b> Payload-only mode withholds "
    "repository, workflow, branch and commit, because that is the precise condition "
    "the separability rate is defined over.",
]))

# ---- 6. Findings
story.append(PageBreak())
story.append(P("6 &nbsp; Measured findings", "h1"))
story.append(P("6.1 &nbsp; The deepest-app-frame signal is mostly unavailable", "h2"))
story.append(P(
    "The specification calls the deepest application frame \"the single most stable "
    "and most causally meaningful signal in a stack trace\" and assigns it a "
    "clustering weight of 0.60. Measured over the corpus:"
))
fr_rows = [["Framework", "Failures", "With a frame", "With app frame", "Rate (Wilson 95%)"]]
for f in facts["frames"]:
    fr_rows.append([f["framework"], str(f["n"]), str(f["frames"]), str(f["app"]),
                    interval(f["rate"])])
tot = facts["framesTotal"]
fr_rows.append(["total", str(tot["n"]), str(tot["frames"]), str(tot["app"]),
                interval(tot["rate"])])
t = table(fr_rows, [92, 60, 76, 82, 140],
          align={1: "RIGHT", 2: "RIGHT", 3: "RIGHT"})
t.setStyle(TableStyle([
    ("FONT", (0, len(fr_rows) - 1), (-1, len(fr_rows) - 1), "Helvetica-Bold", 8.6),
    ("BACKGROUND", (0, len(fr_rows) - 1), (-1, len(fr_rows) - 1), BAND),
]))
story.append(t)
story.append(Spacer(1, 8))
story.append(P(
    "The split is the finding, not the total. Playwright end-to-end failures have "
    "<b>no</b> application frame at all: the stack's only frame is the spec file, "
    "which classifies as test code, because the failure happened inside Playwright's "
    "own machinery acting on behalf of the test. Unit-test frameworks are the "
    "opposite &mdash; pytest and vitest supply one more often than not."
))
story.append(P(
    "So the 0.60 weight is not wrong, but the signal is unavailable for exactly the "
    "workload that produces the most failures per run. Clustering evaluation must "
    "therefore report per-framework F1; an aggregate would be dominated by the "
    "end-to-end case where the signal is missing entirely, and would say nothing "
    "about the case where it is present.",
    "pull",
))

story.append(P("6.2 &nbsp; Defects that only real CI data exposed", "h2"))
story.append(P(
    "Each of these passed hand-written fixtures and failed on real artifacts. They "
    "are recorded because the pattern &mdash; plausible code, wrong on real input "
    "&mdash; is the thing the corpus exists to catch."
))
story.extend(bullets([
    "<b>Raw ESC is illegal in XML 1.0</b>, in raw form and as a character "
    "reference, yet Playwright, pytest and several Maven reporters write ANSI colour "
    "codes into JUnit XML anyway. A strict parser rejected files that real runners "
    "really produce. Whole escape sequences are now removed at the stream level, "
    "counted, and reported &mdash; removing only the ESC byte would leave "
    "<font face='Courier'>[2m</font> as literal text and defeat the ANSI rule "
    "downstream.",
    "<b>The loose assertion rule swallowed whole messages.</b> It reduced every "
    "pytest failure to <font face='Courier'>AssertionError: &lt;val&gt;</font>, "
    "which would have collapsed unrelated failures into one cluster and inflated "
    "false positives. Narrowed to recognised expected/actual constructs, with "
    "literal collapsing split into its own ablatable rule.",
    "<b>JVM frames carry the package in the function name</b>, not the file path, "
    "so checking only the path classified "
    "<font face='Courier'>org.junit.runners.ParentRunner</font> as application code "
    "&mdash; the exact frame that must read as framework noise.",
    "<b>Vitest emits frames marked with a heavy arrow</b> rather than "
    "<font face='Courier'>at&nbsp;</font>, so crux parsed zero frames from them and "
    "discarded a real application frame. Found only because a framework count looked "
    "suspiciously easy to pass.",
    "<b>A property test caught a chunk-boundary bug</b> in the ANSI sanitizer: an "
    "OSC escape split across a stream chunk was mis-detected as complete and "
    "shredded. The result now provably does not depend on how the stream was "
    "chunked.",
]))

story.append(P("6.3 &nbsp; A correction", "h2"))
story.append(P(
    "An earlier draft of this analysis reported the app-frame signal as absent from "
    "<i>every</i> failure, and reported three frameworks by counting "
    "<font face='Courier'>junit</font> as one. Both were wrong. The first was partly "
    "a missing Vitest parser rather than a property of the data; the second counted "
    "a <i>format</i> &mdash; emitted by pytest, jest, vitest and surefire alike "
    "&mdash; as though it identified a framework. Only an adapter whose name is "
    "genuinely framework-specific now counts as evidence, and the unidentified "
    "remainder is reported alongside rather than folded in."
))

# ---- 7. Limitations
story.append(PageBreak())
story.append(P("7 &nbsp; Limitations", "h1"))
story.append(P(
    "Maintained under a standing rule: if something cannot be implemented correctly "
    "yet, document the limitation, provide a safe fallback, and add a roadmap entry "
    "&mdash; never pretend. Each entry below names its fallback, so none is a silent "
    "failure. The full list lives in docs/limitations.md."
))
lim = [
    ("Playwright JSON is parsed whole, not streamed",
     "The blob report streams line by line, but the JSON reporter emits one "
     "document and crux has no incremental JSON parser. Capped at 256 MiB.",
     "Explicit SIZE_LIMIT error naming the blob reporter, never an OOM."),
    ("JUnit cannot express retries",
     "Surefire rerun elements are parsed when present, but a producer that cannot "
     "emit them looks identical to a run where no retry happened.",
     "capabilities().retries is false, so downstream treats absence as "
     "uninformative rather than as evidence."),
    ("Duplicate testcases are treated as retries",
     "Genuinely ambiguous: some producers mean a retry, others mean two "
     "parameterized cases sharing a label.",
     "Both preserved as separate attempts, with a warning."),
    ("Frame ordering is inferred per dialect",
     "Python and pytest print outermost-first; V8, JVM, Go and Ruby print "
     "innermost-first. A stack mixing dialects may be ordered wrongly.",
     "Reversal triggers on a majority of Python-parsed frames."),
    ("Shard index is the artifact's position",
     "The provider does not report which shard produced an artifact.",
     "Claims only 'these came from different uploads'; no machine identity or "
     "clock-skew correction is derived from it."),
    ("Unidentified-licence repositories are skipped",
     "GitHub reports NOASSERTION for a LICENSE it cannot classify. This excludes "
     "some of the richest JUnit XML sources found.",
     "Reported separately from 'no licence', and overridable explicitly."),
]
lim_rows = [["Limitation", "Why", "Safe fallback"]]
for a, b, c in lim:
    lim_rows.append([Paragraph(f"<b>{a}</b>", S["small"]),
                     Paragraph(b, S["small"]), Paragraph(c, S["small"])])
story.append(table(lim_rows, [128, 172, 150]))

# ---- 8. Roadmap
story.append(PageBreak())
story.append(P("8 &nbsp; Phases and gates", "h1"))
story.append(P(
    "Each phase has a numeric gate. The next phase does not begin with the current "
    "gate unmet &mdash; if a gate is missed, the number actually achieved is "
    "reported instead."
))
ph = [
    ("0", "Evidence", "current",
     "Corpus and evidence document.",
     "Separability >= 60%, inter-labeler agreement >= 80%."),
    ("1", "Core, single-run", "",
     "Parsing, normalization, fingerprinting, clustering, deterministic "
     "classification, analyze and explain. Git tiers 1-2.",
     "Pairwise F1 >= 0.80; fingerprint stability >= 99%; zero normalization "
     "collisions; 10k results < 5 s; per-category precision >= 0.85."),
    ("2", "Distribution", "",
     "GitHub Action, PR comment, Checks, npx install, cross-platform binaries.",
     "Clean install on macOS, Linux and Windows on ARM64 and x64, verified in CI."),
    ("3", "History", "",
     "SQLite, rollups, test identity with alias review, flakiness engine.",
     "Rename recall >= 90% at precision >= 98%; flake precision >= 0.85; "
     "historical query < 1 s over 10M attempts."),
    ("4", "Change intelligence", "",
     "Git tiers 1-3, risk model, ownership, components, PostgreSQL.",
     "Risk correlation published, or marked uncalibrated in the UI itself."),
    ("5", "Selection and dashboard", "",
     "Coverage mapping, learned correlation, test selection, dashboard.",
     "Selection recall >= 95% on a time-ordered forward replay across >= 200 runs."),
    ("6", "Ecosystem", "",
     "Plugin SDK, pytest, Cypress, AI providers, OpenTelemetry correlation.",
     "—"),
]
ph_rows = [["", "Phase", "Scope", "Gate"]]
for n, name, mark, scope, gate in ph:
    label = f"<b>{name}</b>" + (f"<br/><font color='#8a4b1f'>{mark}</font>" if mark else "")
    ph_rows.append([n, Paragraph(label, S["small"]),
                    Paragraph(scope, S["small"]), Paragraph(gate, S["small"])])
story.append(table(ph_rows, [16, 92, 158, 184]))

story.append(P("8.1 &nbsp; Explicitly out of scope for Phase 1-2", "h2"))
story.append(P(
    "Dashboard, server, AI, PostgreSQL, plugin SDK, flakiness, risk, selection, "
    "quality score, demo application, telemetry &mdash; regardless of how easy any "
    "of them looks."
))

# ---- 9. Commitments
story.append(P("9 &nbsp; Standing commitments", "h1"))
story.append(P("9.1 &nbsp; Privacy", "h2"))
story.append(P(
    "<b>No telemetry. Not opt-out, not anonymous, none.</b> This is permanent and "
    "is stated in the README. Three clearly separated modes, and the CLI states "
    "which one it is in: local (nothing leaves the machine), server (data goes to "
    "your own deployment), AI (a specified payload goes to a configured provider). "
    "Everything works air-gapped except AI and the GitHub integration."
))
story.append(P("9.2 &nbsp; The AI boundary", "h2"))
story.append(P(
    "crux is fully useful with AI disabled, and AI is off by default. It may only "
    "rephrase deterministic findings, rank existing hypotheses, propose fixes for a "
    "human to read, and summarise computed statistics. It may never invent a commit, "
    "log line, test result, metric, owner or fingerprint; every AI claim must "
    "reference an evidence id that resolves, and a claim whose ids do not resolve is "
    "dropped before display. AI never takes an action &mdash; no merging, closing, "
    "quarantining or suppressing &mdash; regardless of configuration."
))
story.append(P("9.3 &nbsp; No fabricated numbers", "h2"))
story.append(P(
    "No placeholders, no mocks presented as working, no hard-coded demo output. "
    "Every number a user sees is computed or cited. No hand-written sample output "
    "ships, in the README or anywhere else &mdash; it will be wrong, and it is the "
    "first thing a sceptical reader checks. This document is generated from the "
    "code and the corpus for the same reason."
))

# ---- 10. Running it
story.append(PageBreak())
story.append(P("10 &nbsp; Running it", "h1"))
story.append(P(
    "Node 20+ and pnpm 10+. Node 25 no longer bundles corepack, so pnpm is "
    "installed directly."
))
story.append(Paragraph(
    "npm i -g pnpm@10<br/>"
    "pnpm install<br/>"
    "pnpm build<br/>"
    "pnpm test",
    S["code"],
))
story.append(P("Building and measuring the corpus:", "body"))
story.append(Paragraph(
    "gh auth login<br/>"
    "pnpm corpus harvest --repos corpus/sources.txt --runs-per-repo 25<br/>"
    "pnpm corpus status<br/>"
    "<br/>"
    "pnpm corpus label --labeler alice --context full<br/>"
    "pnpm corpus label --labeler bob&nbsp;&nbsp;&nbsp;--context payload-only<br/>"
    "<br/>"
    "pnpm corpus agreement --a alice --b bob<br/>"
    "pnpm corpus separability --full alice --payload bob<br/>"
    "pnpm corpus baseline --labeler alice",
    S["code"],
))
story.append(P("10.1 &nbsp; The next measurement", "h2"))
story.append(P(
    "The baseline spike is deliberately sequenced <i>before</i> the 1000-label "
    "investment. Label 50 failures across 8 multi-failure runs, cluster with the "
    "crudest possible rule &mdash; exact loose-fingerprint match, no graph, no "
    "weights &mdash; and measure pairwise F1. It costs two days and is the "
    "highest-information move available."
))
story.append(table(
    [["Naive F1", "Conclusion"],
     ["near 0.75", "The weighted graph is over-engineering. Ship the simple thing."],
     ["near 0.30", "The problem is genuinely hard, and we know before building the full corpus."],
     ["near 0.05", "The payload does not carry the signal. Stop and reconsider."]],
    [70, 380],
))
story.append(Spacer(1, 10))
story.append(P(
    f"The harness for this is implemented and tested; it has no labels to score "
    f"against. Of the {status['runs']} runs harvested, "
    f"{status['runsWithAtLeast5Failures']} carry five or more failures, which is the "
    f"class that contributes most of the pair signal.",
    "small",
))

story.append(P("10.2 &nbsp; Reading the exit codes", "h2"))
story.append(P(
    "0 pass, 1 gate failed, <b>2 insufficient data to evaluate</b>, 3 execution "
    "error. Two is not one: failing a build because the tool lacked data is how "
    "tools get removed from pipelines."
))


# ---------------------------------------------------------------------------


def decorate(canvas, doc):
    canvas.saveState()
    w, h = A4
    canvas.setStrokeColor(RULE)
    canvas.setLineWidth(0.4)
    canvas.line(20 * mm, 16 * mm, w - 20 * mm, 16 * mm)
    canvas.setFont("Helvetica", 7.6)
    canvas.setFillColor(MUTED)
    canvas.drawString(20 * mm, 11 * mm, "crux — project documentation")
    canvas.drawRightString(w - 20 * mm, 11 * mm, f"page {doc.page}")
    if doc.page > 1:
        canvas.setFont("Helvetica", 7.6)
        canvas.drawString(20 * mm, h - 12 * mm, COMMIT.split(" ")[0])
    canvas.restoreState()


doc = BaseDocTemplate(
    OUT, pagesize=A4,
    leftMargin=20 * mm, rightMargin=20 * mm,
    topMargin=18 * mm, bottomMargin=22 * mm,
    title="crux — project documentation",
    author="The crux Authors",
    subject="Gate 0: ground truth before product code",
)
frame = Frame(doc.leftMargin, doc.bottomMargin,
              doc.width, doc.height, id="body")
doc.addPageTemplates([PageTemplate(id="main", frames=[frame], onPage=decorate)])
doc.build(story)
print(f"wrote {OUT}")
